CREATE TABLE "exchange_rate" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamptz DEFAULT 'now()',
  "crypto_currency_Id" varchar,
  "fiat_currency_acronym" varchar,
  "exchanage_rate" varchar NOT NULL
);

CREATE INDEX ON "exchange_rate" ("fiat_currency_acronym");

CREATE INDEX ON "exchange_rate" ("crypto_currency_Id");

CREATE INDEX ON "exchange_rate" ("created_at");

