// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type ExchangeRate struct {
	ID                  int32          `json:"id"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	CryptoCurrencyId    sql.NullString `json:"crypto_currency_Id"`
	FiatCurrencyAcronym sql.NullString `json:"fiat_currency_acronym"`
	ExchanageRate       string         `json:"exchanage_rate"`
}
