// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetCurrentCryptoExchangeRate(ctx context.Context, cryptoCurrencyId sql.NullString) ([]GetCurrentCryptoExchangeRateRow, error)
	GetCurrentCryptoFiatRate(ctx context.Context, arg GetCurrentCryptoFiatRateParams) (GetCurrentCryptoFiatRateRow, error)
	GetCurrentExchangeRates(ctx context.Context) ([]GetCurrentExchangeRatesRow, error)
	GetExchangeRateHistory(ctx context.Context, arg GetExchangeRateHistoryParams) ([]GetExchangeRateHistoryRow, error)
	InsertExchangeRate(ctx context.Context, arg InsertExchangeRateParams) (ExchangeRate, error)
}

var _ Querier = (*Queries)(nil)
